name: Compile Nexus Tools
on:
  workflow_dispatch:

jobs:
  compile_linux:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Install Dart SDK
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https -y
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update
          sudo apt install dart -y
      - name: Compile Dart executable
        run: |
          cd $GITHUB_WORKSPACE
          dart pub get
          dart compile exe "./bin/main.dart" -o "./nexustools"
      # Upload binary
      - name: Upload Dart executable
        uses: actions/upload-artifact@v2
        with:
          name: nexustools-linux-x64
          path: nexustools
  compile_windows:
    runs-on: windows-latest
    steps:
      - name: Install Dart SDK
        run: |
          choco install dart-sdk
      - uses: actions/checkout@v2
      - name: Compile Dart executable
        run: |
          C:\tools\dart-sdk\bin\dart pub get
          C:\tools\dart-sdk\bin\dart compile exe "bin\main.dart" -o "nexustools.exe"
      - name: Upload Dart executable
        uses: actions/upload-artifact@v2
        with:
          name: nexustools-windows-x64
          path: nexustools.exe
  compile_reactos:
    runs-on: windows-latest
    steps:
      - name: Install Dart SDK
        run: |
          choco install dart-sdk --forcex86
      - uses: actions/checkout@v2
      - name: Compile Dart executable
        run: |
          C:\tools\dart-sdk\bin\dart pub get
          C:\tools\dart-sdk\bin\dart compile jit-snapshot "bin\main.dart" -o "nexustools"
      - name: Upload Dart executable
        uses: actions/upload-artifact@v2
        with:
          name: nexustools-reactos-x32
          path: nexustools
  compile_macos:
    runs-on: macos-latest
    steps:
      - name: Install Dart SDK
        run: |
          brew tap dart-lang/dart
          brew install dart
      - uses: actions/checkout@v2
      - name: Compile Dart executable
        run: |
          dart pub get
          dart compile exe "./bin/main.dart" -o "./nexustools"
      - name: Upload Dart executable
        uses: actions/upload-artifact@v2
        with:
          name: nexustools-macos-x64
          path: nexustools